project_id = "ihvqhjrrahgyunmfvtrp"

[functions.oauth-token]
verify_jwt = false

[functions.oauth-marketplace-callback]
verify_jwt = false

[functions.ghl-opportunity-webhook]
verify_jwt = false

[functions.ghl-list-pipelines]
verify_jwt = false

[functions.sync-ghl-sub-accounts]
verify_jwt = false

